### PR TITLE
Reworking mention plugin

### PR DESCRIPTION
**Pull request by DiggesT**
In this PR I used Lexical Playground [new](https://lexical.dev/docs/demos/plugins/mentions) example of Mentions plugin, and makes it works correctly.

### CODE REVIEW

**Comment by DiggesT** [comment]
There is an error with `ImageNode.tsx`. It uses `<MentionsPlugin />` right [here](https://github.com/ozanyurtsever/verbum/blob/master/src/nodes/ImageNode.tsx#L264).
Trying to find out how to fix it. Maybe should copy [new](https://lexical.dev/docs/demos/plugins/images) Images Plugin example from Lexical?

**Comment by DiggesT** [comment]
Updated image plugin.
Failed to compile: You must set "output.dir" instead of "output.file" when generating multiple chunks. @ozanyurtsever, do you see this error before, can you help me?
To reproduce this error try: `npm start`.

image

**Comment by DiggesT** [comment]
There were dependency conflicts while running `npm install` with `@excalidraw/excalidraw` 0.11.x version.
Updated it to latest.

**Comment by DiggesT** [comment]
Rollup error fixed, with `inlineDynamicImports` parameter. But this is [deprecated](https://rollupjs.org/configuration-options/#deprecated-options) parameter, unfortunately i can't find the better solution.

@ozanyurtsever, please test it before merge.
Also I see that you are very busy and don't have time for development your Verbum project. I really like this project and I'm trying to support it, maybe you can give me admin permissions for speed up the development process.

**Comment by ozanyurtsever** [comment]
Hello,

Sorry for the late response and you are right, I will be busy for a while in the following weeks, but hopefully I will come back for this project.

I appreciate your continuous effort and I will give you write permission so that you can maintain the project with me.

**Pull request merged**
