### PR TITLE
Update Lexical to 0.7.5

### PR DESCRIPTION
**Pull request by DiggesT**
Hey, @ozanyurtsever , there is update Lexical to 0.7.5.
Using playground example for [RichTextPlugin](https://github.com/facebook/lexical/commit/89a4593cc0fd213f1a5655f464461a4d2d43c294#diff-5fe38a0be9fab29258b73969f550654a5d2cff18342ffeac7009eaaf6c44035eL102-R107) and [AutoScrollPlugin](https://github.com/facebook/lexical/commit/15b3ead2f0a150238d969b17899984b6f0ade83d#diff-0a36225a5598840bcd21dbf4c555503ceff01c21da3a98dba460ccb4de2f06faL120-L135).

### CODE REVIEW

**Comment by DiggesT** [comment]
`No loader is configured for ".woff" files`
Actually, i don't have an idea how to fix it. @ozanyurtsever, can you help me, please?

**Comment by ozanyurtsever** [comment]
> `No loader is configured for ".woff" files` Actually, i don't have an idea how to fix it. @ozanyurtsever, can you help me, please?

Hello @DiggesT, I reviewed your pull request and didn't encounter any error as you mentioned. Can you explain how can I reproduce the same error?

**Comment by DiggesT** [comment]
Hello @ozanyurtsever, this error occurs on GitHub PR checkouts, below on this page.
I didn't mention it earlier, sorry.

**Comment by DiggesT** [comment]
Right [here](https://github.com/ozanyurtsever/verbum/actions/runs/3883835899/jobs/6625609824#step:3:210).

**Comment by ozanyurtsever** [comment]
I don't think that error is related to your pull request, that is something I need to resolve with the GitHub Actions configurations. I will accept this pull request since I couldn't find any critical error.

**Pull request merged**
