### PR TITLE
Update Lexical to 0.5.0

### PR DESCRIPTION
**Pull request by DiggesT**
Hey, @ozanyurtsever , there is update Lexical to 0.5.0.

### CODE REVIEW

**Comment by Boye95** [comment]
@DiggesT I'd also love verbum to be updated to 0.5.0

**Comment by Mobuis** [comment]
src/nodes/ExcalidrawNode/index.tsx
```
if (!editor.isEditable) {
  return;
}
```
@DiggesT should not be this ?

**Comment by DiggesT** [comment]
Hi @Mobuis, i think yes, it should. Because `isReadOnly` and `isEditable` have the opposite meaning.
If `isReadOnly()` return `true`, then `isEditable` will return `false`, so we need `!` here. 
Lexical team do the [same](https://github.com/facebook/lexical/commit/06c3e6160cac44f1cdbe3113655bd8d00d1e3195#diff-4788b7f3d98315e661afeac2921fe3bf3826ec36c9e76e1f77090ac891f258e4L110-R116) changes.

**Comment by Mobuis** [comment]
> Hi @Mobuis, i think yes, it should. Because `isReadOnly` and `isEditable` have the opposite meaning. If `isReadOnly()` return `true`, then `isEditable` will return `false`, so we need `!` here. Lexical team do the [same](https://github.com/facebook/lexical/commit/06c3e6160cac44f1cdbe3113655bd8d00d1e3195#diff-4788b7f3d98315e661afeac2921fe3bf3826ec36c9e76e1f77090ac891f258e4L110-R116) changes.

Hi, you should remove the brackets, that's what I meant :)

**Pull request merged**
